#!/bin/sh

UPLOAD_URL=$1
KEY=`/etc/init.d/fastd show_key mesh_vpn`
WGETC=`which wget`
VERSION=$(cat /etc/freifunk_version)
MAC=$(uci get freifunk.@node[0].nodeid)
while [ 1 = 1 ]
do
        $WGETC "nodeid=${MAC}&key=${KEY}&fw_version=${VERSION}" $UPLOAD_URL -O - && break
	sleep 30
done
