#!/bin/sh

UPLOAD_URL=$1
KEY=`/usr/sbin/fastd --machine-readable --show-key -c /tmp/fastd/secret.mesh_vpn.conf`
WGETC=`which wget`
VERSION=$(cat /etc/freifunk_version)
MAC=$(uci get freifunk.node.nodeid)
while [ 1 = 1 ]
do
        $WGETC "nodeid=${MAC}&key=${KEY}&fw_version=${VERSION}" $UPLOAD_URL -O - && break
	sleep 30
done
